# Generated by Django 3.2.10 on 2022-07-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('A', 'ACTION'), ('S', 'SCI-FI'), ('a', 'ADVENTURE'), ('C', 'COMEDY'), ('D', 'DRAMA')], max_length=1),
        ),
    ]
